name: build-host
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    name: ${{ matrix.image.name }}
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        image:
          - path: images/host-fedora-41
            name: host-fedora-41
          - path: images/host-ubuntu-plucky
            name: host-ubuntu-plucky
          - path: images/host-debian-trixie
            name: host-debian-trixie
          - path: images/host-centos-10
            name: host-centos-10

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo sed -i 's/noble/plucky/g' /etc/apt/sources.list.d/ubuntu.sources
          sudo apt update
          sudo apt install -y mkosi

      - name: Build ${{ matrix.image.name }}
        run: |
          sudo mkosi --image-id=${{ matrix.image.name }} -C ${{ matrix.image.path }}/ cat-config
          sudo mkosi --image-id=${{ matrix.image.name }} -C ${{ matrix.image.path }}/ summary
          sudo mkosi --image-id=${{ matrix.image.name }} -C ${{ matrix.image.path }}/ build

      - name: Upload image
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.image.name }}
          path: |
            ${{ matrix.image.path }}/${{ matrix.image.name }}.efi
          retention-days: 7
